name: Test

on:
  push:
    branches: [ master ]
    
jobs:
  killcontainers:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Kill All Containers
        run: docker-compose down
      - name: Check running containers
        run: docker ps -a
  
  client:
    needs: killcontainers
    runs-on: self-hosted
    env:
        VUE_APP_API_URL: http://134.122.93.109:5000/api/todos
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i
        working-directory: client
      - run: npm run test:unit
        working-directory: client

  api:
    needs: killcontainers
    runs-on: self-hosted
    env:
        MONGO_URL: 'mongodb+srv://burak:burak@cluster0.d5tzt.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i
        working-directory: api
      - run: npm run test
        working-directory: api

  test:
    needs: [api,client]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose -f "docker-compose.yml" up -d --build
      - name: Check running containers
        run: docker ps -a
