name: Test

on:
  push:
    branches: [ master ]
    
jobs:
  client:
    runs-on: self-hosted
    env:
        VUE_APP_API_URL: http://localhost:5000/api/todos
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i
        working-directory: client
      - run: npm run serve & npx wait-on http://localhost:8080
        working-directory: client

  api:
    runs-on: self-hosted
    env:
        MONGO_URL: 'mongodb+srv://burak:burak@cluster0.d5tzt.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i
        working-directory: api
      - run: npm start
        working-directory: api
